data <- "ec/newecdata.rds"
ecdata <- readRDS(data)
png("ec/plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))	
plot(ecdata$Time, ecdata$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(ecdata$Time, ecdata$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(ecdata$Time, ecdata$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(ecdata$Time, ecdata$Sub_metering_2, type="l", col="red")
lines(ecdata$Time, ecdata$Sub_metering_3, type="l", col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(ecdata$Time, ecdata$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()